export const steps = [
  {
    id: 'Step 1',
    name: 'Personal Information',
    fields: [
      'name.family',
      'name.first',
      'name.middle',
      'permanentAddress.town',
      'permanentAddress.province',
      'civilStatus',
      'dateOfBirth',
      'placeOfBirth',
      'religion.name',
      'religion.baptized',
      'religion.confirmed',
      'married.ceremony',
      'married.isMarried',
    ],
  },
  {
    id: 'Step 2',
    name: 'Education',
    fields: [
      'previousEducation.elementary.name',
      'previousEducation.elementary.town',
      'previousEducation.elementary.province',
      'previousEducation.elementary.year',
      'previousEducation.secondary.name',
      'previousEducation.secondary.town',
      'previousEducation.secondary.province',
      'previousEducation.secondary.year',
      'previousEducation.collegiate.name',
      'previousEducation.collegiate.town',
      'previousEducation.collegiate.province',
      'previousEducation.collegiate.year',
      'previousEducation.graduate.name',
      'previousEducation.graduate.town',
      'previousEducation.graduate.province',
      'previousEducation.graduate.year',
      'academicHonors',
      'extraCurricularActivities',
      'memberInProfessionalOrg',
      'underGraduateGrade',
      'gradeInMajorSubjects',
      'degree.status',
      'degree.desiredDegree',
      'majorFieldUnits',
      'minorFieldUnits',
      'isFullTimeStudent',
      'presentPosition',
      'subjectTaught',
    ],
  },
  { id: 'Step 3', name: 'References', fields: ['references'] },
  {
    id: 'Step 4',
    name: 'Upload Documents',
    fields: [
      'documents.honorableDismissal',
      'documents.tor',
      'documents.generalWeightedAverage',
      'documents.birthCertificate',
      'documents.idPicture',
      'documents.marriageCertificate',
    ],
  },
];
